export const faq_data = [
  {
    question: "Are there any parking available?",
    answer: [
      "The resort provides parking facilities for guests and it is free of charge.",
    ],
  },
  {
    question: "About Room Check-In / Checkout",
    answer: [
      "Room check-in and out will be done at the counter near the entrance of the Main Hall.",
      "Check-In: Saturday (28 Oct), 1.30pm - 2.00pm",
      "Check-Out: Sunday (29 Oct), 12pm - 12.30pm",
      "You can leave your luggage in your car or at the main hall upon arrival before joining Session 1 at 11am.",
      "If the check-in counter is closed, kindly contact Qian Yi (016-9644290) or Phoebe (018-3111107)",
    ],
  },
  {
    question: "Any dresscode for the sessions?",
    answer: [
      "Dress smart and neatly; no slippers and short pants during the sessions.",
      "We will be taking group photos after the session; feel free to set your team's dresscode.",
      "Saturday (2.30pm - 3pm): Serdang, Kepong, USJ, Setapak, Sg Long, Seremban",
      "Saturday (5.00pm - 5.30pm): Kuchai Wonderkids, Young Warrior, General Service & The Blessing.",
      "Sunday (12pm - 12.30pm): All CYC Ministry Crew, CYC Full Timer.",
    ],
  },
  {
    question: "About Kids",
    answer: [
      "For kids aged 4 to 10, we have Kids Program prepared in the hall next to our Main Hall. Please refer to the schedule for the time slot.",
      "Gentle reminder: Pick up your kids within 15 minutes after each session ends. Bring a water bottle and jacket for your kids.",
      "As for kids below 4 and between 11 to 12 years old, they can sit with their parents during the session. However, do ensure the children remain seated and does not create disturbance to the speaker and other attendees.",
    ],
  },
  {
    question: "About Interpretation Services",
    answer: [
      "Should you need interpretation service,",
      "Kindly bring your own earphone for the device.",
      "For device collection or any relavant questions, please contact Andre Him (012-2005297)",
    ],
  },
  {
    question: "About First Aids",
    answer: [
      "Should you require first aid or any medical assistance,",
      "Kindly contact:",
      "Mei Ling (016-626 2598)",
      "Wui Lun (012-799 7189)",
    ],
  },
];

export const groupingList = {
  1: [
    "Cham Ai Wen",
    "Khoh Kien Seong",
    "Leng Zhi Yan",
    "Lim Chuan Jie",
    "Shum Wai Lok",
    "Ting Heng Ching",
    "Chen Jynfung",
    // "Chew Kok Min",
    "Chin Jia Hao",
    "Fu Hang Xin",
    "Jasmin Yeow Yong Jia",
    "Kow Kei Yan",
    "Richard Koh Peng Hong",
    "Lee Poh Ling",
    // "Goh Seow Yen",
    "Cheong Sze Sian",
  ],
  2: [
    "Goh Jonathan",
    "Ng Xiang Fenn",
    "Goh Tai Chin",
    "Kwong Yoke Khuan",
    "Chua Shu Ying",
    "Angeline Tan Ho Yen",
    "Calvin Cheah Choong Guan",
    "Chai Ka Yan",
    "Chong You You",
    "Joey Lee Wing Hoe",
    "Lau Yen Yee",
    "Liew Seen Yee",
    "Low Hon Keong",
    "Toh Kar Wei",
    "Chan Kong San",
  ],
  3: [
    "Lew Mun Yee",
    "Brian Soong Ee Xuan",
    "Chan Wai Yin",
    "Priscilla Lua Sim Yee",
    "Tan Peck Wah",
    "Lim Fung Shen",
    "Abby Chong",
    "Low Lay Yong",
    "Choy Ren Young",
    "Lam Sai Moy",
    "Lee Brich , John",
    "Lim Ming Zhou",
    "Tan Feng Meen",
    "Wong Kar Shean",
    "Hue Li Li",
    // "Tan Peck Er",
  ],
  4: [
    "Lee Suk Yee",
    "Elaine Teoh",
    "Jesse Liew",
    "Lew Khin Phing",
    "Mok Chee Hoong",
    "Wang Hao Hua",
    "Anita Yee",
    "Wong Hing Yee",
    "Wong Pui Chin",
    "Andre Him Jian Zhi",
    "Arthur Ang Ti Shang",
    "Cynthia Ding Chiau Wei",
    "Lee Jin Ouan",
    "Loo Kai Lee",
    "Yew Jia Ying",
    "Yong Shee Mun",
    "Teow Kai Hui",
  ],
  5: [
    "Rachel Yong Pei Han",
    "Lim Sze Mei",
    // "Chong Lik Foong",
    "Tan Lay Kuan",
    "Lam Wai Ken",
    "Soh Chee Ho",
    "Aaron Choong Ji Tseng",
    "Chan Hoong Yuen",
    "Chan Lai Teng",
    "Hoe San Na",
    "Hoo Mei Qi",
    "Hor Yee Chieh",
    "John Hee Wen Jun",
    "Lee Lin Foong",
    "Lim Teng Wei",
    "Lotus Chong Zi Yee",
    "Wong How Han",
  ],
  6: [
    // "Winnie Wong Wai Yee",
    // "Victor Lim Sheng Kai",
    "Lee Kai Xin",
    "Lee Lay Nah",
    // "Choy Lai Yee",
    // "Daniel Yeo",
    // "Seakny Chong",
    // "Abigail Chong Xi En",
    "Chan Kai Chee",
    "Chan Li Kim",
    "Chan Pui Yan",
    "Chan Zhi Xing",
    "Hor Yee Shin",
    "Joseph Tan Kai Uong",
    "Lee Lin Yean",
    "Nai Pui Shan",
    "Thiam Yew Mun",
    "Tan Peck Er",
    "Kevin Ng Kai Man",
  ],
  7: [
    "Chin Ghee Choong",
    "Ong Chee Gang",
    "Liew Geok Moi",
    "Chang Xiang Ying",
    "Cheok Jun Yoon",
    "Cheong Sze Ying",
    "Chhui Chong San",
    "Chong Sue Eng",
    "Iris Wong Wern Yien",
    "Lai Jo Yee",
    "Lee Heng Koo",
    "Loh Pui Yuan",
    "Ng Koon Foong",
    "Soon Mei Shi",
    "Yit Zhan Hao",
    "Phang Zheng Hai",
  ],
  8: [
    "Sik Chia Lun",
    "Chong Li Min",
    "Choo Wei Loon",
    "Jaymes Chua Chuan Hong",
    "Yap Chun Voon",
    "Chin Jin Voon",
    "Chow Kar Yan",
    "Derek Yeow Han Xiang",
    "Foo Yiping",
    "Ivy Yun",
    "Lew Qian Wei",
    "Lickson Ho",
    "Lim Ka Zen",
    "Nicholas Wong Kai Xuan",
    "Wong Wei Heng",
    "Lee Kin Fatt",
    "Wong Pik Yin",
  ],
  9: [
    "Chloe Chin Lih Yiing",
    "Kong Mun Yee",
    "Carrie See",
    "Cheong Shu Wei",
    "Chong You Yuan",
    "Emily Him Min Li",
    "Hew Kah Wai",
    "Hoh Foong Yoke",
    // "Joanna Grace Dorai",
    "Lai Jia En",
    "Liew Chen Feng",
    "Nicole Teo Shung Ern",
    "Oh Yan May",
    "Sharon Ding Chiau Jen",
    "Tai Chu Huang",
    "Tan Siew Mien",
    "Wong Kim Chow",
  ],
  10: [
    "Goh Khen Joon",
    "Ng Shu Tian",
    "Lee Mun Yee",
    "Chin Tzeyin",
    "Claudia Tang Hay Ee",
    "Deva Alexander",
    "Goh Zheng Yang",
    "Kee Yi Thung",
    "Lau Hui Shan",
    "Lee Wee Seng",
    "Liew Yu Jing",
    "Saw Ming Xuan",
    "Tay Guo Jin",
    "Tee Ah Hieong",
    "Wee Wai Ling",
    "Wong Jia Huei",
    "Jenniper Loo Sook Fan",
  ],
  11: [
    "Vinie Ang Weng Nee",
    "Deborah Lam Hooi Tenh",
    "James Lim Qui Meng",
    "Chong Bee Ching",
    "Kong Wui Lun",
    "Christie Micda",
    "Emme Loke Yan Yi",
    "Isabelle Chan Po Teng",
    "Lai Huey Feng",
    "Leng Yek Seng",
    "Lian Yen Yee",
    "Ng Choi Hua",
    "Phan Zhi Xuan",
    "Yee Tzy Lin",
    "Yong Jing Jie",
    // "Joel Wong Xie Zhe",
    "Ooi Seow Hoon",
  ],
  12: [
    "Liow Ji Herng",
    "Toh Wen Rhu",
    "Chin Ming Keat",
    "Amelia Bong Ching Ching",
    "Bryan Lee",
    "Chong Liu Hong",
    "Fong Chung Sang",
    "Jasmine Tang Hay Yuet",
    "Khor Lay Bee",
    // "Lee Yen Theng",
    "Liew Wai Kit",
    "Lim Pin Jiun",
    "Pang See Kiat",
    "Tan Pek Yan",
    "Tang Chua Hoong",
    "Thong Pei Ling",
    "Han Chin Pei",
  ],
  13: [
    "Thong Siew Chie",
    "Heng Yik Hoe",
    "Goh Chui Hoon",
    "How Siok En",
    "Go Jen Yi",
    // "David Ooi",
    "Hoo Ee Choong",
    "Jason Mak Kah Chun",
    "Johnson Chin Yuen Fatt",
    "Koh Weng Kit",
    "Lim Tuck Seong",
    "Tay Sze Kit",
    "Tay Yen Li",
    "Thong Pei Pei",
    "Toh Bee Theng",
    "Yam Pei Qi",
  ],
  14: [
    "Hoh Yoon Yi",
    // "Leong Sheue Chyi",
    "Chung Wai Quan",
    // "Goh Yen Hing",
    "Soon Mei Ling",
    "Ngu Kee Hoe",
    // "Teng Teck Ming",
    "Fong Choong Sheng",
    "Lau Yiew Ming",
    "Lie Wai Kien",
    "Ng Pern Hao",
    "Ng Wei Onn",
    "Soh Ah Hon",
    "Tang Choy Lee",
    "Yeak Nai Hwa",
    // "Chong Lim Fong",
    "Mah Xue Yi",
  ],
  15: [
    "Lew Qian Yi",
    "Choy Mun Yoong",
    // "Kellyn Yaw Kai Hui",
    // "Kok Wah",
    "Tan Kah Joe",
    "Lai Chin Quan",
    "Lee Shereen",
    "Chan Fung Meen",
    "Lie Wen Si",
    "Ng Liang Shin",
    "Ng Ping Ping",
    "Tai Theng Theng",
    "Wong Poh Yee",
    "Yap Meng Teck",
    "Chew Rouh Peng",
  ],
  16: [
    "Chan Yung You",
    "Fong Tim Ci",
    "Lim Xin Ru",
    // "Chong Chee Meng (Sze Xian's Husband)",
    // "Liow Sze Xian",
    "Ng Kuan Hooi",
    "Tan Wei Sin",
    "Beverly Yip Yi-Man",
    "Lee Hui En",
    "Lim Sze Qi",
    "Shawn Pang",
    "Teo Jia Xin",
    "Thong Pui Teng",
    "Toh Chin Yap",
    "Chen Weng Lam",
    "Loi Ying Ying",
  ],
  17: [
    "Loh Mei Chi",
    "Chin Pooi Kee",
    "Raymond Tan Chin Leong",
    "Lim Zhi Tong",
    "Tan Pooi Yin",
    "Chin Yuk Yung Jonathan",
    "Kong Wui Hiung",
    "Ho Wai Tian",
    "Lai Chin Shen",
    "Ng Wei Jing",
    "Shuvia Pang",
    "Tan Li Zhang",
    "Ting Choh Lui",
    "Wong Kok Weng",
    "Yap Hau Earn",
  ],
  18: [
    "Cheong Woon Peng",
    "Lim Mei Yee",
    "Tan Qin Yong",
    "Cheah Chung Hoong",
    "Low Sim Guang",
    "Wee Yee Chee",
    "Cheng Mey Kee",
    "Christine Ho Yen Yen",
    "Chan Chun Keen",
    "Lai Sook Yeen",
    "Ooi Yong Xing",
    "Shimi Mok Hor Yin",
    "Tan Ai Teng",
    "Teo Min Hang",
    "Erwinizan Bin Mugit",
    // "Mah Ter Wyei",
  ],
  19: [
    "Chong Kah Wei",
    "Yap Ai Ling",
    "Ooi Choon Keat",
    "Abby Lim",
    "Cham Ai Lin",
    "Chan Chi Ying",
    "Chow Hwee Lu",
    "Lee Ai Leng",
    "Loh Chin Lai",
    "Pooi Weng Been",
    "Saw Li Hua",
    "Wang Mee Kee",
    "Wong Chin Yeng Jane",
    "Wong Weng Sam",
    "Wong Kin Hou",
  ],
  20: [
    "Siow Tong En",
    "Tang Boon Lian",
    // "Goh Sue Ling",
    "Chan Ze Xuan",
    "Chen Hong Ji",
    "Cheong Suet Yee",
    "Chong Zu Yee",
    "Kimberly Cheng",
    "Liew Yap Kee",
    "Loh Pui Ni",
    "Ng Bee Keow",
    "Sunil Kumar",
    "William Chai Jun Wai",
    "Wong Chu Hui",
    "Wong Khien Fong",
    "Yew Chee Wei",
  ],
  21: [
    "Chin Siew Yin",
    "Chong Jian Sheng",
    "Ng Bao Yi",
    "Chan Li Xuan",
    "Cheok Sin Way",
    "Chong Sze Wei",
    "Dorothea Wong Yen Ning",
    "Loh Xin Kai",
    "Loo Chiew Har",
    "Mok Chee Haw",
    "Tan Yi Xuan",
    "Teo Jia En",
    "Wong Jing Lin",
    "Yap Pei Siang",
    "Yee Chee How",
  ],
  22: [
    "Denise Ding Chiau Jueng",
    "Liew Hern Liang",
    "Ching Seow Ling",
    "Benjamin Ng Zi-Wei",
    "Chang Xin Yi",
    "Fong Jia Shin",
    "Gan Xin Hui",
    "Lee Ching Mei",
    "Lim Hao Zun",
    "Ng Koon Ann",
    "Ong Kar Yen",
    "Soh Wai Hong",
    "Wong Hor Yan",
    "Wong Mun Fong",
    "Yap Kam Seng",
    "Yap Pei Yee",
  ],
  23: [
    "Chong Dickson",
    "Teh Ling Ming",
    "Hui Lee Wei",
    "Teh Boon Liang",
    "Chong Zih Xin",
    "Gan Jeun Kit",
    "Goh Swee Peng",
    "Law Yen Har",
    "Lee Wei Han",
    "Liew Pei Tong",
    "Lim Jia Min",
    "Lim Seng Yong",
    "Peter Ku",
    "Phang Yaw Yih",
    "Tey Theresa",
    "Toh Hui Min",
    "Yap Rose",
  ],
  24: [
    "Yu Enci",
    "Phoon Tzi Cheng",
    "Khor Tet Woei",
    "Jenny Then Tzu Ying",
    "Tan Jue Yu",
    "Liew Ker Shin",
    "Evon Loh",
    "Han Kok Dheng",
    "Joseph Chong Zuo Nian",
    "Kasen Chan",
    "Ng Kok Cheng",
    "Samuel Lee",
    "Soo Kah Meng",
    "Teh Heng Yong",
    "Yap Yuan Joe",
    "Yong",
  ],
  25: [
    "Lim Kai Le",
    "Lee Cheng Yee",
    "Chong Hui Ying",
    "Isaac Chung Ern Xu",
    "Joshua Cheng Jun Hao",
    "Khoo Han Sheng",
    "Lim Soo Sim",
    "Low Chan Yee",
    "Ng Mei Mei",
    "Sue Pei En",
    "Tan Hau Zheng",
    "Tioh Chin Hang",
    "Wang Hao Yong",
    "Wong Yao Huei",
    "Ho Mei Jing",
    "Teressa Tang",
  ],
};
